// vue/src/components/Progress.vue
<script setup>
import { ref } from "vue";
import useNuiEvent from "../composables/useNuiEvent";
import fetch from "../utils/fetch";

const visible = ref(false);
const timerInterval = ref(null);
const setProgressInterval = ref(null);
const status = ref(null);

const label = ref("");
const completedLabel = ref("");
const failedLabel = ref("");
const type = ref("linear");
const color = ref("primary");
const progress = ref(0);

const mockData = {
  label: "Loading2",
  completedLabel: "Completed",
  failedLabel: "Failed",
  type: "circular",
  time: 3000,
};

const clearIntervals = () => {
  if (timerInterval.value) clearInterval(timerInterval.value);
  if (setProgressInterval.value) clearInterval(setProgressInterval.value);
};

const stopProgress = (success) => {
  clearIntervals();

  completedLabel.value = success ? completedLabel.value : failedLabel.value;
  color.value = success ? "success" : "error";
  status.value = success;

  const stop = () => {
    setTimeout(() => {
      visible.value = false;
      // fetch("progressStopped", success)
    }, 500);
  };

  if ((success && progress.value < 100) || (!success && progress.value > 0)) {
    setProgressInterval.value = setInterval(() => {
      if (
        (success && progress.value >= 100) ||
        (!success && progress.value <= 0)
      ) {
        clearInterval(setProgressInterval.value);
        stop();
      } else {
        progress.value += success ? 1 : -1;
      }
    }, 10);
  } else {
    stop();
  }
};

const startProgress = (data) => {
  clearIntervals();

  label.value = data.label.toUpperCase();
  completedLabel.value = data.completedLabel.toUpperCase();
  failedLabel.value = data.failedLabel.toUpperCase();
  type.value = data.type;

  status.value = null;
  color.value = "primary";
  progress.value = 0;
  visible.value = true;

  const interval = data.time / 1000;

  timerInterval.value = setInterval(() => {
    if (progress.value >= 100) {
      stopProgress(true);
    } else {
      progress.value += 0.1;
    }
  }, interval);
};

// useNuiEvent('startProgress', startProgress);
// useNuiEvent('stopProgress', stopProgress);
</script>

<template>
  <v-btn @click="startProgress(mockData)">Toggle</v-btn>
  <v-btn color="red" @click="stopProgress(false)">Cancel</v-btn>
  <div
    v-if="visible"
    class="w-full h-1/2 flex justify-center items-end pb-8 font-semibold text-sm text-white"
  >
    <v-progress-linear
      v-if="type === 'linear'"
      :model-value="progress"
      :color="color"
      height="25"
      rounded-bar="true"
      striped="true"
    >
    <span class="flex justify-center items-center h-full">
      {{ status === null ? label : "" }}
      {{
        status !== null
          ? status === true
            ? completedLabel
            : failedLabel
          : Math.round(progress, 1) + "%"
      }}
    </span>
    </v-progress-linear>
    <div
      v-if="type === 'circular'"
      class="flex flex-col gap-4 justify-center items-center"
    >
      <v-progress-circular
        :size="120"
        :width="10"
        :model-value="progress"
        :color="color"
      >
        {{
          status !== null
            ? status === true
              ? completedLabel
              : failedLabel
            : Math.round(progress, 1) + "%"
        }}
      </v-progress-circular>
      <span>{{ label }}</span>
    </div>
  </div>
</template>

// web/src/components/Progress.tsx
import { useRef, useState } from "react";
import { useNuiEvent } from "../hooks/useNuiEvent";
import { fetchNui } from "../utils/fetchNui";
import { CircularProgress, LinearProgress } from "@mui/joy";
import { useSfx } from "../hooks/useSfx";

export const Progress = () => {
  let timerInterval = useRef<NodeJS.Timeout | null>(null);
  const { playSuccess, playFail } = useSfx();
  const [visible, setVisible] = useState(false);
  const [label, setLabel] = useState<string>("");
  const [type, setType] = useState<"linear" | "circle">("linear");
  const [progress, setProgress] = useState<number>(0);
  const [completedLabel, setCompletedLabel] = useState<string>("COMPLETED");
  const [failedLabel, setFailedLabel] = useState<string>("FAILED");
  const [color, setColor] = useState<"primary" | "success" | "danger">("primary");

  const handleStopProgress = (success: boolean) => {
    if (timerInterval.current) clearInterval(timerInterval.current);
    if (success) playSuccess();
    else playFail();
    setLabel(success ? completedLabel : failedLabel);
    setColor(success ? "success" : "danger");

    const stop = () => {
      setTimeout(() => {
        setVisible(false);
        fetchNui("progressStopped", success);
      }, 1000);
    };

    if (success && progress < 100) {
      const setProgressInterval = setInterval(() => {
        setProgress((prev) => {
          if (prev >= 100) {
            clearInterval(setProgressInterval);
            stop();
            return 100;
          }
          return prev + 1;
        });
      }, 10);
    } else if (!success && progress > 0) {
      const setProgressInterval = setInterval(() => {
        setProgress((prev) => {
          if (prev <= 0) {
            clearInterval(setProgressInterval);
            stop();
            return 0;
          }
          return prev - 1;
        });
      }, 10);
    } else {
      stop();
    }
  };

  useNuiEvent("startProgress", (data) => {
    setLabel(data.label.toUpperCase());
    setCompletedLabel(data.completedLabel.toUpperCase());
    setFailedLabel(data.failedLabel.toUpperCase());
    setType(data.type);
    setColor('primary');
    setProgress(0);

    setVisible(true);

    var interval = data.time / 100;
    var step = 1;

    if (interval >= 100) {
      interval /= 10;
      step /= 10;
    }

    timerInterval.current = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          handleStopProgress(true);
          return 100;
        }
        return prev + step;
      });
    }, interval);
  });

  useNuiEvent("stopProgress", handleStopProgress);

  return (
    visible && (
      <div className="w-1/3 h-full flex justify-center items-end pb-8">
        {type === "circle" && (
          <>
            <div className="flex flex-col gap-2 items-center justify-center">
              <CircularProgress
                variant="soft"
                determinate
                value={progress}
                color={color}
                sx={{
                  "--CircularProgress-size": "80px",
                  "--CircularProgress-thickness": "8px",
                }}
              >
                <span className="font-semibold text-white">
                  {Math.round(progress)}%
                </span>
              </CircularProgress>
              <span className="font-semibold text-white">
                {label && label}
              </span>
            </div>
          </>
        )}
        {type === "linear" && (
          <LinearProgress
            variant="soft"
            size="lg"
            determinate
            value={progress}
            color={color}
            sx={{
              "--LinearProgress-thickness": "24px",
            }}
          >
            <span className="font-semibold mix-blend-difference">
              {label && label} {Math.round(progress)}%
            </span>
          </LinearProgress>
        )}
      </div>
    )
  );
};
